[package]
name = "flappy_bird"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.0",features = ["dynamic_linking"]}
bevy_dylib = "0.15.0"
rand = "0.9.1"

[profile.dev]
opt-level = 1